export {Main} from './Main';
export {Error404} from './Error404';
export {Login} from './auth/Login';
export {Register} from './auth/Register'
export {AllJob} from "./dashboard/AllJob";
export {AddJob} from "./dashboard/AddJob";
export {Statistics} from "./dashboard/Statistics";
export {Profile} from "./dashboard/Profile";
export {EditJob} from "./dashboard/EditJob";
